name: MovieX Pipeline

# Trigger the workflow on pushes to main or pull requests
on:
  push:
    branches:
      - main

# Define the jobs
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint for linting
      - name: Run Linting
        run: npm run lint

      # Step 5: Run tests with Jest
      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './dist'  # Change this if your build output is in a different directory (e.g., 'build' for Create React App)
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token for commit status updates
          production-branch: main  # The branch that triggers deployment
          production-deploy: true  # Ensure this is true to deploy to production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Set this in GitHub Secrets
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Set this in GitHub Secrets

      # Step 6: Build the project
    #   - name: Build Project
    #     run: npm run build

    # Step 7: Deploy to Netlify
